namespace RovOverlay.Desktop.Services;

// Supporter keys (docs/PLAN.md §10): the Settings section, the expiry reminder and the
// line saying the app is not Garena's or Tencent's.
public sealed partial class Loc
{
    private static readonly Dictionary<string, string> SupporterEn = new()
    {
        ["Support.Buy"] = "Get a key",
        ["Support.BuyPrice"] = "Get a key · {0}",
        ["Support.BuySoon"] = "Buying opens soon",
        ["Support.SecureNote"] = "Payment is handled by Stripe. Nuzka never sees your card or bank details.",
        ["Nav.Support"] = "Support",
        ["Support.Title"] = "Support Nuzka",
        ["Support.Lead"] = "Nuzka is free, and stays free: every feature works without paying. Supporters keep it going, and in return their overlays go out clean, without the watermark.",
        ["Support.YourKey"] = "YOUR KEY",
        ["Support.Thanks"] = "Thank you for supporting Nuzka!",
        ["Support.Get"] = "WHAT YOU GET",
        ["Support.Get1"] = "No watermark on any overlay.",
        ["Support.Get2"] = "Your name shown as the supporter in the app.",
        ["Support.Get3"] = "You help pay for new features, fixes and updates.",
        ["Support.Price"] = "PRICE",
        ["Support.Monthly"] = "Monthly",
        ["Support.Yearly"] = "Yearly",
        ["Support.PerMonth"] = "a month",
        ["Support.PerYear"] = "a year",
        ["Support.PriceSoon"] = "Coming soon",
        ["Support.How"] = "HOW TO GET A KEY",
        ["Support.Step1"] = "Press Get a key below. A secure Stripe payment page opens in your browser.",
        ["Support.Step2"] = "Type the name you want on the key, then pay with PromptPay or a card.",
        ["Support.Step3"] = "Your key appears straight away. Press Copy key.",
        ["Support.Step4"] = "Paste it in the box at the top of this page. The watermark goes at once.",
        ["Support.Faq"] = "QUESTIONS",
        ["Support.Q1"] = "Do I need the internet?",
        ["Support.A1"] = "No. The key is checked on this PC, so a broadcast never depends on the internet.",
        ["Support.Q2"] = "What happens when it runs out?",
        ["Support.A2"] = "You get a reminder 7 days before. After that the watermark comes back; everything else keeps working.",
        ["Support.Q3"] = "Can I use it on another PC?",
        ["Support.A3"] = "Yes, on your own PCs: paste the same key there. Please do not share it; a shared key can be switched off.",
        ["Support.Q4"] = "Is anything locked without a key?",
        ["Support.A4"] = "No. Every feature is free. The key only removes the watermark.",
        ["Supporter.Section"] = "SUPPORTER",
        ["Supporter.Hint"] = "The app is free and stays free. Supporters help keep it going, and their key hides the small \"Nuzka\" watermark on every overlay. The key is checked on this PC: no account, and no internet needed during a broadcast.",
        ["Supporter.None"] = "No supporter key. The overlays show a small watermark.",
        ["Supporter.Active"] = "Supporter: {0}, until {1}. No watermark on the overlays.",
        ["Supporter.ActiveSoon"] = "Supporter: {0}, until {1}. Runs out in {2} days.",
        ["Supporter.Expired"] = "The key for {0} ran out on {1}. The watermark is back.",
        ["Supporter.Revoked"] = "The key for {0} has been switched off. The watermark is back.",
        ["Supporter.Broken"] = "The saved key is not valid any more. The watermark is back.",
        ["Supporter.Offline"] = "Waiting for the server…",
        ["Supporter.Paste"] = "Paste your key here (starts with RVS1-)",
        ["Supporter.Use"] = "Use this key",
        ["Supporter.Remove"] = "Remove key",
        ["Supporter.Become"] = "Become a supporter",
        ["Supporter.Thanks"] = "Thank you, {0}! The watermark is gone from every overlay.",
        ["Supporter.RemoveTitle"] = "Remove the supporter key?",
        ["Supporter.RemoveBody"] = "The watermark comes back on every overlay straight away, including any that are on air.",
        ["Supporter.RemoveBody2"] = "Keep a copy of the key if you want to use it again.",
        ["Supporter.Removed"] = "Supporter key removed.",
        ["Supporter.Err.format"] = "That is not a supporter key. Copy the whole key, starting with RVS1-.",
        ["Supporter.Err.signature"] = "That key was not made by Nuzka. Check it was copied completely.",
        ["Supporter.Err.expired"] = "That key has run out.",
        ["Supporter.Err.revoked"] = "That key has been switched off.",
        ["Supporter.RemindSoon"] = "Your supporter key runs out in {0} days ({1}). After that the watermark comes back.",
        ["Supporter.RemindExpired"] = "Your supporter key ran out on {0}. The watermark is back on the overlays.",
        ["Settings.Disclaimer"] = "Nuzka is a fan-made tool for Arena of Valor (RoV). It is not endorsed by Garena or Tencent and does not reflect the views of anyone officially involved in producing or managing Arena of Valor (RoV). Game names, hero images and logos belong to their owners."
    };

    private static readonly Dictionary<string, string> SupporterTh = new()
    {
        ["Support.Buy"] = "รับคีย์",
        ["Support.BuyPrice"] = "รับคีย์ · {0}",
        ["Support.BuySoon"] = "เปิดขายเร็ว ๆ นี้",
        ["Support.SecureNote"] = "การชำระเงินดูแลโดย Stripe แอป Nuzka ไม่เห็นข้อมูลบัตรหรือบัญชีธนาคารของคุณ",
        ["Nav.Support"] = "สนับสนุน",
        ["Support.Title"] = "สนับสนุน Nuzka",
        ["Support.Lead"] = "Nuzka ใช้ฟรีและจะฟรีต่อไป ทุกฟีเจอร์ใช้ได้โดยไม่ต้องจ่าย ผู้สนับสนุนช่วยให้แอปไปต่อได้ และได้ overlay ที่ไม่มีลายน้ำเป็นการขอบคุณ",
        ["Support.YourKey"] = "คีย์ของคุณ",
        ["Support.Thanks"] = "ขอบคุณที่สนับสนุน Nuzka!",
        ["Support.Get"] = "สิ่งที่ได้",
        ["Support.Get1"] = "ไม่มีลายน้ำบนทุก overlay",
        ["Support.Get2"] = "ชื่อของคุณแสดงเป็นผู้สนับสนุนในแอป",
        ["Support.Get3"] = "ช่วยค่าพัฒนาฟีเจอร์ใหม่ แก้บั๊ก และอัปเดต",
        ["Support.Price"] = "ราคา",
        ["Support.Monthly"] = "รายเดือน",
        ["Support.Yearly"] = "รายปี",
        ["Support.PerMonth"] = "ต่อเดือน",
        ["Support.PerYear"] = "ต่อปี",
        ["Support.PriceSoon"] = "เร็ว ๆ นี้",
        ["Support.How"] = "วิธีรับคีย์",
        ["Support.Step1"] = "กด รับคีย์ ด้านล่าง หน้าชำระเงินที่ปลอดภัยของ Stripe จะเปิดในเบราว์เซอร์",
        ["Support.Step2"] = "พิมพ์ชื่อที่อยากให้ขึ้นในคีย์ แล้วจ่ายด้วยพร้อมเพย์หรือบัตร",
        ["Support.Step3"] = "คีย์จะขึ้นทันที กด คัดลอกคีย์",
        ["Support.Step4"] = "วางคีย์ในช่องด้านบนของหน้านี้ ลายน้ำจะหายทันที",
        ["Support.Faq"] = "คำถามที่พบบ่อย",
        ["Support.Q1"] = "ต้องต่ออินเทอร์เน็ตไหม",
        ["Support.A1"] = "ไม่ต้อง คีย์ตรวจในเครื่องนี้เอง การถ่ายทอดจึงไม่ขึ้นกับอินเทอร์เน็ต",
        ["Support.Q2"] = "หมดอายุแล้วเป็นยังไง",
        ["Support.A2"] = "จะมีข้อความเตือนก่อน 7 วัน หลังหมดอายุลายน้ำจะกลับมา ส่วนอื่นใช้ได้ตามปกติ",
        ["Support.Q3"] = "ใช้ในเครื่องอื่นได้ไหม",
        ["Support.A3"] = "ได้ ในเครื่องของคุณเอง วางคีย์เดียวกันได้เลย แต่อย่าแชร์ให้คนอื่น คีย์ที่ถูกแชร์อาจถูกปิดใช้งาน",
        ["Support.Q4"] = "ถ้าไม่มีคีย์ มีอะไรใช้ไม่ได้ไหม",
        ["Support.A4"] = "ไม่มี ทุกฟีเจอร์ใช้ฟรี คีย์แค่เอาลายน้ำออก",
        ["Supporter.Section"] = "ผู้สนับสนุน",
        ["Supporter.Hint"] = "แอปนี้ใช้ฟรีและจะฟรีต่อไป ผู้สนับสนุนช่วยให้แอปไปต่อได้ และคีย์ของผู้สนับสนุนจะซ่อนลายน้ำ \"Nuzka\" เล็ก ๆ บนทุก overlay คีย์ตรวจในเครื่องนี้เอง ไม่ต้องมีบัญชี และไม่ต้องใช้อินเทอร์เน็ตระหว่างถ่ายทอด",
        ["Supporter.None"] = "ยังไม่มีคีย์ผู้สนับสนุน overlay จะมีลายน้ำเล็ก ๆ",
        ["Supporter.Active"] = "ผู้สนับสนุน: {0} ถึง {1} ไม่มีลายน้ำบน overlay",
        ["Supporter.ActiveSoon"] = "ผู้สนับสนุน: {0} ถึง {1} เหลืออีก {2} วัน",
        ["Supporter.Expired"] = "คีย์ของ {0} หมดอายุเมื่อ {1} ลายน้ำกลับมาแล้ว",
        ["Supporter.Revoked"] = "คีย์ของ {0} ถูกปิดใช้งานแล้ว ลายน้ำกลับมาแล้ว",
        ["Supporter.Broken"] = "คีย์ที่บันทึกไว้ใช้ไม่ได้แล้ว ลายน้ำกลับมาแล้ว",
        ["Supporter.Offline"] = "กำลังรอเซิร์ฟเวอร์…",
        ["Supporter.Paste"] = "วางคีย์ที่นี่ (ขึ้นต้นด้วย RVS1-)",
        ["Supporter.Use"] = "ใช้คีย์นี้",
        ["Supporter.Remove"] = "ลบคีย์",
        ["Supporter.Become"] = "ร่วมเป็นผู้สนับสนุน",
        ["Supporter.Thanks"] = "ขอบคุณ {0}! ลายน้ำหายไปจากทุก overlay แล้ว",
        ["Supporter.RemoveTitle"] = "ลบคีย์ผู้สนับสนุน?",
        ["Supporter.RemoveBody"] = "ลายน้ำจะกลับมาบนทุก overlay ทันที รวมถึงอันที่กำลังออกอากาศอยู่",
        ["Supporter.RemoveBody2"] = "เก็บคีย์ไว้ถ้าจะใช้อีกครั้ง",
        ["Supporter.Removed"] = "ลบคีย์ผู้สนับสนุนแล้ว",
        ["Supporter.Err.format"] = "นี่ไม่ใช่คีย์ผู้สนับสนุน คัดลอกคีย์ให้ครบ ตั้งแต่ RVS1-",
        ["Supporter.Err.signature"] = "คีย์นี้ไม่ได้ออกโดย Nuzka ตรวจว่าคัดลอกมาครบ",
        ["Supporter.Err.expired"] = "คีย์นี้หมดอายุแล้ว",
        ["Supporter.Err.revoked"] = "คีย์นี้ถูกปิดใช้งานแล้ว",
        ["Supporter.RemindSoon"] = "คีย์ผู้สนับสนุนของคุณจะหมดอายุในอีก {0} วัน ({1}) หลังจากนั้นลายน้ำจะกลับมา",
        ["Supporter.RemindExpired"] = "คีย์ผู้สนับสนุนของคุณหมดอายุเมื่อ {0} ลายน้ำกลับมาบน overlay แล้ว",
        ["Settings.Disclaimer"] = "Nuzka เป็นเครื่องมือสำหรับ Arena of Valor (RoV) ที่แฟนเกมทำขึ้นเอง ไม่ได้รับการรับรองจาก Garena หรือ Tencent และไม่ได้สะท้อนความเห็นของผู้ที่เกี่ยวข้องกับการผลิตหรือดูแล Arena of Valor (RoV) อย่างเป็นทางการ ชื่อเกม รูปฮีโร่ และโลโก้เป็นของเจ้าของสิทธิ์"
    };
}

// A key's last day, the way people write dates: "27 Oct 2026", or "27 ต.ค. 2569" in Thai,
// which counts years in the Buddhist era.
public static class SupporterDates
{
    public static string Show(string? isoDate)
    {
        if (!DateTime.TryParseExact(isoDate, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture,
                System.Globalization.DateTimeStyles.None, out var date))
            return isoDate ?? "?";
        return date.ToString("d MMM yyyy", Loc.Instance.Culture);
    }
}
